name: getx_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  extended_image: ^8.0.2
  flutter_easyloading: ^3.0.5
  animated_notch_bottom_bar: ^1.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons_maker: ^0.10.2
flutter_icons: { android: launcher_icon, image_path: assets/icon/icon.png, ios: true,
                 flutter_lints: ^1.0.4 }
flutter: 
  uses-material-design: true

